name: Upload to Google Cloud App Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        # uses: google-github-actions/setup-gcloud@master
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: factoree-beta
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          export_default_credentials: true

      - id: Deploy
        name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: factoree-beta

      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies    
      - run: npm ci
      - run: npm test
      - run: 'gcloud app deploy app.yaml --quiet --no-promote --version v1'

      # - run: npm install
      # - run: npm install pm2 -g
      # - run: pm2 start index.js --watch

    #steps:
    #  - uses: actions/checkout@v2
    #  - name: Use Node.js 14
    #    uses: actions/setup-node@v2
    #    with:
    #      node-version: 14
    #  - name: Install dependencies
    #    run: npm ci
    #  - run: npm test
      # - name: Deploy to App Engine
      #   id: deploy
      #   uses: google-github-actions/deploy-appengine@v0.2.0
      #   with:
      #     deliverables: app.yaml cron.yaml
      #     version: v1
      #     project_id: ${{ secrets.GCP_PROJECT }}
      #     credentials: ${{ secrets.GCP_CREDENTIALS }}